# Generated by Django 5.1.1 on 2024-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device1Switch', models.BooleanField()),
                ('device2Switch', models.BooleanField()),
                ('device3Switch', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FloatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todayUsage', models.FloatField()),
                ('monthUsage', models.FloatField()),
                ('device1Usage', models.FloatField()),
                ('device2Usage', models.FloatField()),
                ('device3Usage', models.FloatField()),
            ],
        ),
    ]
